version: "3"

networks:
    backend:
        driver: bridge

volumes:
    mysql-database:
        driver: local
    mailcatcher-data:
        driver: local
    vendor:
        driver: local
    node_modules:
        driver: local

services:
    web:
        build:
            context: .
        volumes:
            - ".:/var/www/html:cached"
            - "vendor:/var/www/html/vendor"
            - "node_modules:/var/www/html/node_modules"
        ports:
            - 8000:8000
        networks:
            - backend

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laraveldb
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: secret
        volumes:
            - mysql-database:/var/lib/mysql
        networks:
            - backend

    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - "1080:1080"
            - "1025:1025"
        networks:
            - backend

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql
        ports:
            - 10083:80
        depends_on:
            - mysql
        volumes:
            - /sessions
        networks:
            - backend
